Class Alias should not be loaded in the service Provider
This causes error in phpunit Tests:


ErrorException: Cannot redeclare class Fractal.


It should be added in the config/app.php

'Fractal'  => Cyvelnet\Laravel5Fractal\Facades\Fractal::class,